-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE chats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  note_id INTEGER,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch()),
  FOREIGN KEY (note_id) REFERENCES notes(id)
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  latitude REAL,
  longitude REAL,
  location_name TEXT,
  mood TEXT DEFAULT 'calm',
  mode TEXT DEFAULT 'trace',
  is_private INTEGER DEFAULT 0,
  ai_summary TEXT,
  created_at INTEGER DEFAULT (unixepoch())
, emotion TEXT DEFAULT 'calm', image_url TEXT);

-- INDEXS

CREATE INDEX chats_created_at_idx ON chats(created_at);

CREATE INDEX chats_note_id_idx ON chats(note_id);

CREATE INDEX chats_user_id_idx ON chats(user_id);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX notes_created_at_idx ON notes(created_at);

CREATE INDEX notes_mode_idx ON notes(mode);

CREATE INDEX notes_user_id_idx ON notes(user_id);
