// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, real, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const notes = sqliteTable("notes", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	content: text().notNull(),
	latitude: real(),
	longitude: real(),
	locationName: text("location_name"),
	mood: text().default("calm"),
	mode: text().default("trace"),
	isPrivate: integer("is_private").default(0),
	aiSummary: text("ai_summary"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	emotion: text().default("calm"),
	imageUrl: text("image_url"),
},
(table) => [
	index("notes_created_at_idx").on(table.createdAt),
	index("notes_mode_idx").on(table.mode),
	index("notes_user_id_idx").on(table.userId),
]);

export const chats = sqliteTable("chats", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	noteId: integer("note_id").references(() => notes.id),
	role: text().notNull(),
	content: text().notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("chats_created_at_idx").on(table.createdAt),
	index("chats_note_id_idx").on(table.noteId),
	index("chats_user_id_idx").on(table.userId),
]);

